### ISSUE TITLE
Integration with BiocPy/SummarizedExperiment

### ISSUE THREAD

**Issue by jkanche** [complextissue/pytximport#15]
Hi developers, 

Awesome effort to port tximport to Python. On a similar vein, I've been implementing some of the core R/Bioconductor datastructures in Python - [BiocPy](https://github.com/biocpy/.). I would love to find ways to collaborate, especially interfacing with [SummarizedExperiment](https://github.com/BiocPy/SummarizedExperiment) objects. 

Please let me know if you have any questions.

**Comment by maltekuehl** [comment]
Hi,

thanks for your interest in pytximport & the idea. So far, we had no plans to integrate with `SummarizedExperiment`, but I believe that it could be of interest and should be fairly straightforward to do so, so we definitely welcome pull requests.

Based on my understanding of `SummarizedExperiment`, you would just have to add a couple lines of code to support it as another `output_format`/`output_type` (format being file extension when saving to disk, type being return type of the function). Relevant code parts are in `core/_tximport.py` and start here: https://github.com/complextissue/pytximport/blob/d386a3a565a2492674bfe83fd9dac2826dd79c31/pytximport/core/_tximport.py#L443

Since we would like to keep the install size of `pytximport` somewhat limited, it would be best if `SummarizedExperiment` was an optional dependency with adequate error handling when it's not installed. Ideally, a PR should also support use through the CLI version of `pytximport`, the relevant lines start here:
https://github.com/complextissue/pytximport/blob/d386a3a565a2492674bfe83fd9dac2826dd79c31/pytximport/_cli.py#L132

Before merging any changes into `main`, unit tests would also have to be implemented but we are happy to help add them on our side if you prefer not to touch that part of the codebase.

If you don't wish to implement any PR yourself but would still like to see `SummarizedExperiment` supported, please let us know & we will discuss internally whether we should add it to our roadmap.

Best,
Malte
